"""initial schema

Revision ID: 60c3c3c552bc
Revises: 
Create Date: 2026-03-10 16:13:00.789166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60c3c3c552bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition_season',
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_code', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_code'], ['seasons.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('competition_id', 'season_code')
    )
    op.create_table('competition_season_team',
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_code', sa.Text(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_code'], ['seasons.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('competition_id', 'season_code', 'team_id')
    )
    op.create_table('player_position',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('position_code', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_code'], ['positions.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'position_code')
    )
    op.drop_index(op.f('uq_player_one_primary_position'), table_name='player_positions', postgresql_where='(is_primary = true)')
    op.drop_table('player_positions')
    op.drop_index(op.f('idx_cst_lookup'), table_name='competition_season_teams')
    op.drop_table('competition_season_teams')
    op.drop_table('competition_seasons')
    op.alter_column('competitions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('competitions', 'country_code',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('competitions', 'level',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('nationalities', 'code',
               existing_type=sa.CHAR(length=3),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('player_nationalities', sa.Column('nationality_code', sa.Text(), nullable=False))
    op.drop_index(op.f('uq_player_one_primary_assoc'), table_name='player_nationalities', postgresql_where='(is_primary = true)')
    op.drop_constraint(op.f('player_nationalities_code_fkey'), 'player_nationalities', type_='foreignkey')
    op.drop_constraint(op.f('fk_player_nationalities_nationality'), 'player_nationalities', type_='foreignkey')
    op.create_foreign_key(None, 'player_nationalities', 'nationalities', ['nationality_code'], ['code'], ondelete='CASCADE')
    op.drop_column('player_nationalities', 'code')
    op.alter_column('player_stats', 'source',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('idx_player_stats_metrics'), table_name='player_stats', postgresql_using='gin')
    op.drop_index(op.f('idx_player_stats_player'), table_name='player_stats')
    op.drop_index(op.f('idx_player_stats_season'), table_name='player_stats')
    op.drop_constraint(op.f('player_stats_punique'), 'player_stats', type_='unique')
    op.drop_index(op.f('uq_player_stats_key'), table_name='player_stats')
    op.create_index(op.f('ix_player_stats_player_id'), 'player_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_stats_team_id'), 'player_stats', ['team_id'], unique=False)
    op.create_unique_constraint('uq_player_season_source', 'player_stats', ['player_id', 'team_id', 'season_code', 'source'])
    op.drop_constraint(op.f('fk_player_stats_player'), 'player_stats', type_='foreignkey')
    op.drop_constraint(op.f('player_stats_team_id_fkey'), 'player_stats', type_='foreignkey')
    op.drop_constraint(op.f('fk_player_stats_season'), 'player_stats', type_='foreignkey')
    op.alter_column('players', 'short_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('players', 'slug',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('players', 'sofascore_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('players', 'fotmob_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('players', 'transfermarkt_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('players', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('players', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_players_fbref_id'), table_name='players')
    op.drop_index(op.f('idx_players_full_name'), table_name='players')
    op.drop_index(op.f('idx_players_sofascore_id'), table_name='players')
    op.drop_index(op.f('uq_players_slug'), table_name='players')
    op.drop_index(op.f('uq_players_transfermarkt_id'), table_name='players')
    op.create_unique_constraint(None, 'players', ['sofascore_id'])
    op.create_unique_constraint(None, 'players', ['slug'])
    op.create_unique_constraint(None, 'players', ['fbref_id'])
    op.create_unique_constraint(None, 'players', ['fotmob_id'])
    op.alter_column('positions', 'line',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('seasons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'tm_team_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'tm_team_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('seasons', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('positions', 'line',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_constraint(None, 'players', type_='unique')
    op.create_index(op.f('uq_players_transfermarkt_id'), 'players', ['transfermarkt_id'], unique=True)
    op.create_index(op.f('uq_players_slug'), 'players', ['slug'], unique=True)
    op.create_index(op.f('idx_players_sofascore_id'), 'players', ['sofascore_id'], unique=False)
    op.create_index(op.f('idx_players_full_name'), 'players', ['full_name'], unique=False)
    op.create_index(op.f('idx_players_fbref_id'), 'players', ['fbref_id'], unique=False)
    op.alter_column('players', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('players', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('players', 'transfermarkt_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('players', 'fotmob_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('players', 'sofascore_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('players', 'slug',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('players', 'short_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(op.f('fk_player_stats_season'), 'player_stats', 'seasons', ['season_code'], ['code'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('player_stats_team_id_fkey'), 'player_stats', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('fk_player_stats_player'), 'player_stats', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_player_season_source', 'player_stats', type_='unique')
    op.drop_index(op.f('ix_player_stats_team_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_player_id'), table_name='player_stats')
    op.create_index(op.f('uq_player_stats_key'), 'player_stats', ['player_id', 'season_code', 'source'], unique=True)
    op.create_unique_constraint(op.f('player_stats_punique'), 'player_stats', ['team_id', 'season_code', 'player_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_player_stats_season'), 'player_stats', ['season_code'], unique=False)
    op.create_index(op.f('idx_player_stats_player'), 'player_stats', ['player_id'], unique=False)
    op.create_index(op.f('idx_player_stats_metrics'), 'player_stats', ['metrics'], unique=False, postgresql_using='gin')
    op.alter_column('player_stats', 'source',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('player_nationalities', sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'player_nationalities', type_='foreignkey')
    op.create_foreign_key(op.f('fk_player_nationalities_nationality'), 'player_nationalities', 'nationalities', ['code'], ['code'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('player_nationalities_code_fkey'), 'player_nationalities', 'nationalities', ['code'], ['code'])
    op.create_index(op.f('uq_player_one_primary_assoc'), 'player_nationalities', ['player_id'], unique=True, postgresql_where='(is_primary = true)')
    op.drop_column('player_nationalities', 'nationality_code')
    op.alter_column('nationalities', 'code',
               existing_type=sa.Text(),
               type_=sa.CHAR(length=3),
               existing_nullable=False)
    op.alter_column('competitions', 'level',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('competitions', 'country_code',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('competitions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('competition_seasons',
    sa.Column('competition_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('season_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.code'], name=op.f('competition_seasons_competition_id_fkey')),
    sa.ForeignKeyConstraint(['season_code'], ['seasons.code'], name=op.f('competition_seasons_season_code_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('competition_id', 'season_code', name=op.f('competition_seasons_pkey'))
    )
    op.create_table('competition_season_teams',
    sa.Column('competition_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('season_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.code'], name=op.f('competition_season_teams_competition_id_fkey')),
    sa.ForeignKeyConstraint(['season_code'], ['seasons.code'], name=op.f('competition_season_teams_season_code_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.tm_team_id'], name=op.f('competition_season_teams_team_id_fkey')),
    sa.PrimaryKeyConstraint('competition_id', 'season_code', 'team_id', name=op.f('competition_season_teams_pkey'))
    )
    op.create_index(op.f('idx_cst_lookup'), 'competition_season_teams', ['competition_id', 'season_code'], unique=False)
    op.create_table('player_positions',
    sa.Column('player_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('position_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_position_player'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('player_positions_player_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_code'], ['positions.code'], name=op.f('fk_player_position_position'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_code'], ['positions.code'], name=op.f('player_positions_position_code_fkey')),
    sa.PrimaryKeyConstraint('player_id', 'position_code', name=op.f('player_positions_pkey'))
    )
    op.create_index(op.f('uq_player_one_primary_position'), 'player_positions', ['player_id'], unique=True, postgresql_where='(is_primary = true)')
    op.drop_table('player_position')
    op.drop_table('competition_season_team')
    op.drop_table('competition_season')
    # ### end Alembic commands ###
