from typing import Protocol

from app.infrastructure.db.models.competition import Competition

class CompetitionRepository(Protocol):
    async def get_by_id(self, competition_id: int) -> Competition | None:
        ...
    async def get_by_code(self, code: str) -> Competition | None:
        ...
    async def list(self, filters: dict) -> list[Competition]:
        ...
    async def save(self, competition: Competition) -> Competition:
        ...
    async def delete(self, competition_id: int) -> None:
        ...
