from typing import Protocol
from uuid import UUID

from app.infrastructure.db.models.player_stats import PlayerStats

class PlayerStatsRepository(Protocol):
    async def get_by_id(self, stats_id: UUID) -> PlayerStats | None:
        ...
    async def get_by_player(self, player_id: UUID, season_code: str | None=None) -> list[PlayerStats]:
        ...
    async def get_by_team(self, team_id: UUID, season_code: str | None=None) -> list[PlayerStats]:
        ...
    async def upsert(self, stats: PlayerStats) -> PlayerStats:
        ...
    async def bulk_upsert(self, stats_list: list[PlayerStats]) -> int:
        ...
    async def delete(self, stats_id: UUID) -> None:
        ...