from typing import Protocol
from uuid import UUID

from app.infrastructure.db.models.team import Team

class TeamRepository(Protocol):
    async def get_by_id(self, team_id: UUID) -> Team | None:
        ...
    async def get_by_tm_id(self, tm_team_id: int) -> Team | None:
        ...
    async def list(self, filters: dict) -> list[Team]:
        ...
    async def save(self, team: Team) -> Team:
        ...
    async def delete(self, team_id: UUID) -> None:
        ...
    async def exists(self, team_id: UUID) -> bool:
        ...