from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.infrastructure.db.models.player import Player

class SQLAlchemyPlayerRepository:
    def __init__(self, session: AsyncSession) -> None:
        self.session = session

    #Recover an object for primary key. Uses internal session cache: if the object is already
    #present, return it without issuing a SQL query. Otherwise, issues a SQL query to locate the 
    #object based on the primary key, and returns the object, or None if not found.
    async def get_by_id(self, player_id: UUID) -> Player | None:
        return await self.session.get(Player, player_id)
    
    async def get_by_slug(self, slug: str) -> Player | None:
        result = await self.session.execute(select(Player).where(Player.slug == slug))
        return result.scalar_one_or_none()
    
    async def list(self, filters: dict) -> list[Player]:
        stmt = select(Player)
        if name:= filters.get("name"):
            stmt = stmt.where(Player.full_name.ilike(f"%{name}%"))
        if foot:= filters.get("preferred_foot"):
            stmt = stmt.where(Player.preferred_foot == foot)
        result = await self.session.execute(stmt)
        return list(result.scalars().all())
    
    async def save(self, player: Player) -> Player:
        self.session.add(player)

        #flush() instead of commit() because we want to return the player with the id generated by 
        #the database, but we don't want to commit the transaction yet.
        #Commit will be handled by the unit of work, which will call commit() after all operations are 
        #done. This allows us to have multiple operations in a single transaction, and if any of them 
        #fail, we can roll back the entire transaction.
        await self.session.flush()
        await self.session.refresh(player)
        return player
    
    async def delete(self, player_id: UUID) -> None:
        player = await self.get_by_id(player_id)
        if(player):
            await self.session.delete(player)

    async def exists(self, player_id: UUID) -> bool:
        result = await self.session.get(Player, player_id)
        return result is not None